### ISSUE TITLE
Encryptor class has gotten worse according to Code Climate

### ISSUE THREAD

**Issue by monfresh** [attr-encrypted/encryptor#19]
Hi. I noticed you have a Code Climate badge, so I'm assuming you care about the quality of this repo's code. I noticed that the latest commits have resulted in a worse grade on Code Climate. Is this something you care about and are planning to address?

The general rule of thumb I follow when working on projects that use Code Climate is that a pull request that results in a worse grade does not get merged.

I was wondering what your thoughts are on this matter.

**Comment by saghaulor** [comment]
I do care about code quality. Ideally the quality only improves. You may have noticed that the new feature that was merged added some complexity which adversely affected out score. Hopefully we can correct that. However, in this particular case, I think having a bit more code complexity as of cost of more security is worth it. Thanks for raising this issue. I'll try to follow your suggestion in the future.
