### ISSUE TITLE
Setting a new cipher algorithm is not overriding the default algorithm

### ISSUE THREAD

**Issue by levolvel** [attr-encrypted/encryptor#24]
When running through the basic example on a windows machine and setting the cipher to use **aes-256-cbc**

<pre>cipher = OpenSSL::Cipher.new('<b>aes-256-cbc</b>')
cipher.encrypt # Required before '#random_key' or '#random_iv' can be called. http://ruby-doc.org/stdlib-2.0.0/libdoc/openssl/rdoc/OpenSSL/Cipher.html#method-i-encrypt
secret_key = cipher.random_key # Insures that the key is the correct length respective to the algorithm used.
iv = cipher.random_iv # Insures that the IV is the correct length respective to the algorithm used.
salt = SecureRandom.random_bytes(16)
encrypted_value = Encryptor.encrypt(value: 'some string to encrypt', key: secret_key, iv: iv, salt: salt)
decrypted_value = Encryptor.decrypt(value: encrypted_value, key: secret_key, iv: iv, salt: salt)
</pre>

It errors out at with the following:

<pre>[10] pry(main)> encrypted_value=Encryptor.encrypt(value: 'some string to encrypt', key: secret_key, iv: iv, salt: salt)
RuntimeError: unsupported cipher algorithm (<b>aes-256-gcm</b>)
from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/encryptor-3.0.0/lib/encryptor.rb:57:in initialize'</pre>

It appears that setting a new cipher algorithm is not overriding the default algorithm.

**Comment by saghaulor** [comment]
@levolvel I'm not very familiar with using Ruby on Windows. Perhaps Ruby for Windows doesn't support AES-GCM algorithms?

However, you can pass the algorithm option to Encryptor to specify what algorithm you would like to use. Based on what you specified above, it looks like you're trying to use 'aes-256-cbc'. In that case, just do this:

``` ruby
algorithm = 'aes-256-cbc'
encrypted_value = Encryptor.encrypt(value: 'some string to encrypt', key: secret_key, iv: iv, salt: salt, algorithm: algorithm)
decrypted_value = Encryptor.decrypt(value: encrypted_value, key: secret_key, iv: iv, salt: salt, algorithm)
```
