### ISSUE TITLE
Unencrypt via database query

### ISSUE THREAD

**Issue by kylesziv** [attr-encrypted/encryptor#25]
Is there any way to unencrypt an encrypted column through active record? Or more importantly, is there a way to unencrypt straight with SQL?

**Comment by saghaulor** [comment]
@kylesziv I don't know if you've looked at attr_encrypted, but it overwrites the accessors that ActiveRecord writes to transparently encrypt/decrypt.

In regards to doing crypto in straight SQL, it is possible. At the column level, there are several supported functions:

https://dev.mysql.com/doc/refman/5.5/en/encryption-functions.html
https://www.postgresql.org/docs/9.4/static/pgcrypto.html

There are also table or database level solutions. You're welcome to explore those for yourself.
